package eu.sanprojects.daltonj.ui;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.JToolBar;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Insets;

public class MainForm {
    private JPanel imagePanel;
    private JPanel rootComponent;
    private JButton getScreenshotButton;
    private JButton openFileButton;
    private JToggleButton grayscaleToggleButton;
    private JToggleButton deuteranopiaToggleButton;
    private JToggleButton tritanopiaToggleButton;
    private JToggleButton protanopiaToggleButton;
    private JToggleButton normalToggleButton;
    private JButton clipboardButton;


    public MainForm() {
        ButtonGroup filtersButtonGroup = new ButtonGroup();
        filtersButtonGroup.add(grayscaleToggleButton);
        filtersButtonGroup.add(deuteranopiaToggleButton);
        filtersButtonGroup.add(tritanopiaToggleButton);
        filtersButtonGroup.add(protanopiaToggleButton);
        filtersButtonGroup.add(normalToggleButton);
    }

    public JPanel getImagePanel() {
        return imagePanel;
    }

    public JPanel getRootComponent() {
        return rootComponent;
    }

    public JButton getGetScreenshotButton() {
        return getScreenshotButton;
    }

    public JButton getOpenFileButton() {
        return openFileButton;
    }

    public JToggleButton getGrayscaleButton() {
        return grayscaleToggleButton;
    }

    public JToggleButton getDeuteranopiaButton() {
        return deuteranopiaToggleButton;
    }

    public JToggleButton getTritanopiaButton() {
        return tritanopiaToggleButton;
    }

    public JToggleButton getProtanopiaButton() {
        return protanopiaToggleButton;
    }

    public JToggleButton getNormalButton() {
        return normalToggleButton;
    }

    public JButton getClipboardButton() {
        return clipboardButton;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootComponent = new JPanel();
        rootComponent.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        final JToolBar toolBar1 = new JToolBar();
        toolBar1.setFloatable(false);
        rootComponent.add(toolBar1);
        final JLabel label1 = new JLabel();
        label1.setText("From:");
        toolBar1.add(label1);
        getScreenshotButton = new JButton();
        getScreenshotButton.setText("Screenshot");
        toolBar1.add(getScreenshotButton);
        clipboardButton = new JButton();
        clipboardButton.setText("Clipboard");
        toolBar1.add(clipboardButton);
        openFileButton = new JButton();
        openFileButton.setText("File");
        toolBar1.add(openFileButton);
        final JLabel label2 = new JLabel();
        label2.setText("Filter:");
        toolBar1.add(label2);
        normalToggleButton = new JToggleButton();
        normalToggleButton.setText("Normal");
        toolBar1.add(normalToggleButton);
        deuteranopiaToggleButton = new JToggleButton();
        deuteranopiaToggleButton.setText("Deuteranopia");
        toolBar1.add(deuteranopiaToggleButton);
        protanopiaToggleButton = new JToggleButton();
        protanopiaToggleButton.setText("Protanopia");
        toolBar1.add(protanopiaToggleButton);
        tritanopiaToggleButton = new JToggleButton();
        tritanopiaToggleButton.setText("Tritanopia");
        toolBar1.add(tritanopiaToggleButton);
        grayscaleToggleButton = new JToggleButton();
        grayscaleToggleButton.setText("Grayscale");
        toolBar1.add(grayscaleToggleButton);
        imagePanel = new JPanel();
        imagePanel.setLayout(new CardLayout(0, 0));
        rootComponent.add(imagePanel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootComponent;
    }

}
